### ISSUE TITLE
No contact address given

### ISSUE THREAD

**Issue by Korodny** [steamknight/NEONnoir#1]
Neither the game, nor its source code nor the itch.io page list any means of contacting the author I'd have loved to give some feedback, but the hurdles are too high.

**Comment by steamknight** [comment]
Hi, you can contact me on twitter @massprodgames or you can email me at mass@massproduced.games. Or, if you like, you can leave feedback on the itch.io page or here in GitHub.

Thank you for taking the time to reach out to me.
