### ISSUE TITLE
Typos in the text

### ISSUE THREAD

**Issue by Korodny** [steamknight/NEONnoir#2]
Below are some typos I encountered while playing the game. Square brackets indicate characters or words that need to be removed, normal brackets show characters or words that need to be added:

description when manipulating the ATM: scan[!]ned
blue haired guy talking: alway(s)
player to danni: how [do] (did) you two meet
danni talking: for an[d] old woman
B19 description: There should (have) be(en) people working
player to Danni: need you(r) help
Credits: [goodest] (best) girl

**Comment by steamknight** [comment]
Thank you for this! I'll update the code to fix these typos. I won't be able to update the game on the itch page until the jam judging period ends in 12 days. Hopefully I'll have this and a few other bugfixes taken care of by then.

**Comment by steamknight** [comment]
Thank for bringing those typos to my attention!
