### ISSUE TITLE
gutter.neon only as a binary?

### ISSUE THREAD

**Issue by Korodny** [steamknight/NEONnoir#3]
gutter.neon seems to contain the game logic and text. It is only available in binary form, apparently? That's a shame, because it would make a very good example for how to use the adventure engine and its scripting language.

**Comment by steamknight** [comment]
The `gutter.neon` file is generated by the NeonNoirEditor. It takes in two files: `gutter.json` (which defines all the locations, scenes, hit locations, and dialogues) and the `gutter.nscript` files (which defines in "noirscript" all of the actions that will happen when something gets clicked.

Noirscript is an assembly-ish language that gets compiled into bytecode by the editor. The "engine" will look at that bytecode and make calls within the engine. Unfortunately I don't have any documentation on noirscript, but you can see what it looks like if you look at gutter.nscript.

I hope this helps. Eventually I'd like to fix all the issues with these tools so people can easily make their own games.
